// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmadulkhxarugucmtwut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtYWR1bGtoeGFydWd1Y210d3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjk3NjgsImV4cCI6MjA1NzkwNTc2OH0.auJ9ydEuuUIpbMMn8IoHI6ekS_Cymw8mejiF9TriPb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});