// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvzmqkdgapkbktgtlhco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2em1xa2RnYXBrYmt0Z3RsaGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTQzODUsImV4cCI6MjA2NjY5MDM4NX0.Oq8XQcEuSBkpnOQB6S3FHvuUz6yJekoaV4Q7Ngs5Ix8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});